// Products
const GET_PRODUCTS = "GET_PRODUCTS";
const GET_PRODUCTS_BY_NAME = "GET_PRODUCTS_BY_NAME";
const GET_PRODUCTS_BY_ID = "GET_PRODUCTS_BY_ID";

// Categories
const GET_CATEGORIES = "GET_CATEGORIES";

// Cart
const CART_ADD_PRODUCT = "CART_ADD_PRODUCT";
const CART_REMOVE_PRODUCT = "CART_REMOVE_PRODUCT";

// Filter
const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";

// Order
const ORDER_BY_PRICE = "ORDER_BY_PRICE";

export default {
  GET_PRODUCTS,
  GET_PRODUCTS_BY_NAME,
  GET_CATEGORIES,
  ORDER_BY_PRICE,
  FILTER_BY_CATEGORY,
  CART_ADD_PRODUCT,
  CART_REMOVE_PRODUCT,
};
